domains: "storymap.knightlab.com"
cnames: "storymapjs.knightlab.com"

static_bucket: "media.knightlab.com"
gunicorn_reload: False

ssl:
  ssl_certificate: "/etc/nginx/ssl/knightlab/knightlab-bundle.crt"
  ssl_certificate_key: "/etc/nginx/ssl/knightlab/knightlab-com.key"

init_env_prd:
  STATIC_URL: "//media.knightlab.com/{{ project_name }}/"
  CDN_URL: "//cdn.knightlab.com/libs/storymapjs/latest/"
  DB_ENGINE__DEFAULT: "mongo"
  DB_NAME__DEFAULT: "storymapjs"
  DB_HOST__DEFAULT: "prod-mongo1.knilab.com"
  DB_PORT__DEFAULT: "27017"

# Note that env vars set in the upstart config will also be set when using the
# modified manage.py file for db migration and custom management commands
init_env: "{{ init_env_common|combine(init_env_prd) }}"
