project_name: StoryMapJS
gitdeploy_version: "1.0.4"
port: 9014
python: python2
type: flask
pwd: "{{ lookup('env', 'PWD') }}"
# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  STORYMAPJS_DIRECTORY: "{{ deploy_dir }}"

  # Flask specific
  FLASK_SECRET_KEY: "{{ vault_flask_secret_key }}"
  FLASK_SETTINGS_MODULE: "core.settings"
  FLASK_SETTINGS_FILE: "core/settings.py"
  AWS_STORAGE_BUCKET_NAME: "{{ vault_aws_storage_bucket_name }}"
  AWS_STORAGE_BUCKET_URL: "{{ vault_aws_storage_bucket_url }}"
  AWS_STORAGE_BUCKET_KEY: "{{ vault_aws_storage_bucket_key }}"
  AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ vault_aws_secret_access_key }}"
  GOOGLE_CLIENT_ID: "{{ vault_google_client_id }}"
  GOOGLE_CLIENT_SECRET: "{{ vault_google_client_secret }}"
  ADMINS: "{{ vault_admins | join(' ') }}"
  ALLOWED_IDS: "{{ vault_allowed_ids }}"

# Flask specific configs
static_dir: "{{ deploy_dir }}/static"

application_dir: "{{ deploy_dir }}" # application dir could be a subdirectory
service_name: "apps/storymap"

# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
env_setup_script: "{{ deploy_dir }}/env.sh"
env_run_script: "{{ deploy_dir }}/env_run.sh"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "core.wsgi:application"
static_service: "s3"
static_dest: "s3://{{ static_bucket }}/{{ project_name }}"

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env

nginx_template: "{{ config_dir }}/custom_nginx.j2"

# environment keys must match deployment branch names. Value is the name
# of the branch to be merged into this environment during deployment.
supported_envs:
  stg: master
  prd: stg
